[package]
name = "tauri-leptos-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
publish.workspace = true

[dependencies]
clap.workspace = true
tokio.workspace = true
tracing.workspace = true
leptos.workspace = true
tauri-leptos-core.workspace = true
tauri-leptos-ui = { path = "../ui", features = ["ssr"] }

[lints]
workspace = true
